sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  apt:
    sources:
    packages:
      - build-essential
      - pandoc
      - figlet
      - graphviz
# command to install dependencies
install:
  - pip install .
  - pip install -r ./testlib/test_reqs.txt
# command to run tests
script:
    - python ./test_sake.py
    - cd functests/test3/ && python ./functest.py
